trainer: !include "../../trainers/gpu.yaml"
model:
  module: src.models
  class_name: UltrasoundSegmentationModel
  config:
    network: !include "../../nets/ukad_variants/ukad_b.yaml"
    criterion: !include "../../losses/composite.yaml"
    optimizer: !include "../../optimizers/adam_seg.yaml"
data:
  train_dataloaders:
  - !include "../../data/isic/train_dataloader.yaml"
  val_dataloaders:
  - !include "../../data/isic/val_dataloader.yaml"
