module: src.models.nets
class_name: LKMUNet
config:
  in_ch: 3
  out_ch: 1
  filters: [32, 64, 128, 256, 512, 512]
  strides: [1, 2, 2, 2, 2, 2]
  blocks_per_stage: 2
  decoder_blocks_per_stage: 2
  window_scale: 8
  d_state: 16
  d_conv: 4
  expand: 2
